name: commutr
version: 1.0.0+1
publish_to: none
description: Download articles and content to read on your commute
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  get_storage: any
  webview_flutter: any
  html: any
  background_fetch: any
  webcontent_converter: any
  path_provider: any
  flutter_downloader: any
  flutter_gradients_reborn: any
  google_fonts: any
  pdf_viewer_plugin: any
  super_cupertino_navigation_bar: any
  flutter_spinkit: any
  json_annotation: any
  cupertino_icons: ^1.0.2
  cupertino_rounded_corners: any
  get: 4.6.6
  http: any
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  json_serializable: any
  flutter_test: 
    sdk: flutter
  build_runner: any

flutter: 
  uses-material-design: true

