# Generated by Django 5.0 on 2023-12-14 12:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='source_name')),
                ('rss_url', models.URLField(db_column='rss_feed_url')),
                ('political_leaning', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
        ),
        migrations.CreateModel(
            name='NewsSourceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128)),
                ('news_source', models.ForeignKey(db_column='news_source_id', on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='commutr.newssource')),
            ],
            options={
                'db_table': 'news_source_topic',
                'unique_together': {('news_source', 'topic')},
            },
        ),
    ]
