# Generated by Django 4.1.13 on 2023-12-21 13:10

import commutr.db.news_source_keys
import commutr.db.news_topic_model
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_column="source_id",
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="source_name", editable=False, max_length=128
                    ),
                ),
                (
                    "rss_url",
                    models.URLField(db_column="source_rss_feed_url", editable=False),
                ),
                (
                    "political_leaning",
                    models.FloatField(
                        db_column="source_political_leaning",
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "latest_article",
                    models.DateTimeField(
                        db_column="source_latest_article",
                        default=datetime.datetime(1970, 1, 1, 0, 0),
                        null=True,
                    ),
                ),
                (
                    "keys",
                    djongo.models.fields.EmbeddedField(
                        db_column="source_keys",
                        default={
                            "headline_key": "title",
                            "published_key": datetime.datetime(
                                2023, 12, 21, 13, 10, 15, 553243
                            ),
                            "url_key": "link",
                        },
                        model_container=commutr.db.news_source_keys.NewsSourceKeys,
                    ),
                ),
                (
                    "topics",
                    djongo.models.fields.ArrayField(
                        db_column="source_topics",
                        default=[],
                        model_container=commutr.db.news_topic_model.NewsTopic,
                    ),
                ),
            ],
            options={
                "db_table": "news_source",
            },
        ),
        migrations.CreateModel(
            name="NewsSourceKeys",
            fields=[
                (
                    "url_key",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline_key", models.CharField(editable=False, max_length=128)),
                (
                    "image_key",
                    models.CharField(
                        default=None, editable=False, max_length=128, null=True
                    ),
                ),
                (
                    "subtitle_key",
                    models.CharField(
                        default=None, editable=False, max_length=128, null=True
                    ),
                ),
                (
                    "author_key",
                    models.CharField(
                        default=None, editable=False, max_length=128, null=True
                    ),
                ),
                ("published_key", models.CharField(editable=False, max_length=128)),
                (
                    "topics_key",
                    models.CharField(
                        default=None, editable=False, max_length=128, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsTopic",
            fields=[
                (
                    "topic",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        db_column="article_headline", editable=False, max_length=512
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        db_column="article_subtitle",
                        editable=False,
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        db_column="article_image_url", editable=False, null=True
                    ),
                ),
                (
                    "published",
                    models.DateTimeField(db_column="article_published", editable=False),
                ),
                ("url", models.URLField(db_column="article_url", editable=False)),
                (
                    "author",
                    models.CharField(
                        db_column="article_author", editable=False, max_length=256
                    ),
                ),
                (
                    "topics",
                    djongo.models.fields.ArrayField(
                        db_column="article_topics",
                        default=[],
                        model_container=commutr.db.news_topic_model.NewsTopic,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        db_column="news_source_id",
                        editable=False,
                        max_length=128,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="commutr.newssource",
                    ),
                ),
            ],
            options={
                "db_table": "news_article",
                "ordering": ["-published"],
            },
        ),
    ]
