# Generated by Django 5.0 on 2023-12-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newssource',
            table='news_source',
        ),
    ]
