# Generated by Django 5.0 on 2023-12-14 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0002_alter_newssource_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='author_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='categories_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='headline_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='image_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='published_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='subtitle_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='topics_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='newssource',
            name='url_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('headline', models.CharField(db_column='article_headline', max_length=512)),
                ('subtitle', models.CharField(db_column='article_subtitle', max_length=2048)),
                ('image', models.URLField(db_column='article_image_url')),
                ('published', models.DateTimeField(db_column='article_published')),
                ('url', models.URLField(db_column='article_url')),
                ('source', models.ForeignKey(db_column='news_source_id', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='commutr.newssource')),
            ],
            options={
                'db_table': 'news_article',
            },
        ),
    ]
