# Generated by Django 5.0 on 2023-12-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0003_newssource_author_key_newssource_categories_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssource',
            name='categories_key',
        ),
    ]
