# Generated by Django 5.0 on 2023-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0004_remove_newssource_categories_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.URLField(db_column='article_image_url', null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='subtitle',
            field=models.CharField(db_column='article_subtitle', max_length=2048, null=True),
        ),
    ]
