# Generated by Django 5.0 on 2023-12-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0005_alter_newsarticle_image_alter_newsarticle_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='headline_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='published_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='url_key',
            field=models.CharField(max_length=128),
        ),
    ]
