# Generated by Django 5.0 on 2023-12-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0006_alter_newssource_headline_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published']},
        ),
    ]
