# Generated by Django 5.0 on 2023-12-14 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0008_newsarticlecontent_newsarticletopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticlecontent',
            name='article',
            field=models.OneToOneField(db_column='news_article_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content', serialize=False, to='commutr.newsarticle'),
        ),
    ]
