# Generated by Django 5.0 on 2023-12-14 21:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0009_alter_newsarticlecontent_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='headline',
            field=models.CharField(db_column='article_headline', editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.URLField(db_column='article_image_url', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='published',
            field=models.DateTimeField(db_column='article_published', editable=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=models.ForeignKey(db_column='news_source_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='commutr.newssource'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='subtitle',
            field=models.CharField(db_column='article_subtitle', editable=False, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(db_column='article_url', editable=False),
        ),
        migrations.AlterField(
            model_name='newsarticlecontent',
            name='article',
            field=models.OneToOneField(db_column='news_article_id', editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='content', serialize=False, to='commutr.newsarticle'),
        ),
        migrations.AlterField(
            model_name='newsarticletopic',
            name='article',
            field=models.ForeignKey(db_column='news_article_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='commutr.newsarticle'),
        ),
        migrations.AlterField(
            model_name='newsarticletopic',
            name='topic',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='author_key',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='headline_key',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='image_key',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='published_key',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='subtitle_key',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='topics_key',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='newssource',
            name='url_key',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
