# Generated by Django 5.0 on 2023-12-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutr', '0010_alter_newsarticle_headline_alter_newsarticle_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(db_column='article_author', default='Joe Rourke', editable=False),
            preserve_default=False,
        ),
    ]
